#!/bin/bash

for i in \
  .aliases \
  .envvars \
  .zshrc \
  .zshrc-functions \
  .zshrc-peco \
  .zshrc-prompt \
  .zshrc-warnings \
  .vimrc \
  .vimrc-neocomplete \
  .vimrc-neosnippet \
  .tigrc \
  .gemrc \
  .pryrc \

do
  if [ ! -s $HOME/$i ]; then
    ln -sf $PWD/$i $HOME/$i
  fi
done

if [ ! -d $HOME/.config/nvim ]; then
  mkdir -p $HOME/.config/nvim
fi
if [ ! -s $HOME/.config/nvim/init.vim ]; then
  ln -sf $PWD/.vimrc $HOME/.config/nvim/init.vim
fi

if [ ! -d $HOME/.emacs.d ]; then
  mkdir $HOME/.emacs.d
fi
if [ ! -s $HOME/.emacs.d/init.el ]; then
  ln -sf $PWD/.emacs.d_init.el $HOME/.emacs.d/init.el
fi
if [ ! -s $HOME/.emacs.d/packages.el ]; then
  ln -sf $PWD/.emacs.d_packages.el $HOME/.emacs.d/packages.el
fi

if [ ! -d $HOME/.lein ]; then
  mkdir $HOME/.lein
fi
if [ ! -f $HOME/.lein/profiles.clj ]; then
  cp $PWD/.lein_profiles.clj $HOME/.lein/profiles.clj
fi

if [ ! -d $HOME/.w3m ]; then
  mkdir $HOME/.w3m
fi
if [ ! -s $HOME/.w3m/keymap ]; then
  ln -sf $PWD/.w3m/keymap $HOME/.w3m/keymap
fi

if [ `which git` ]; then
  if [ ! -f $HOME/.gitignore ]; then
    ln -sf $PWD/.gitignore-global $HOME/.gitignore
  fi
  git config --global user.name ka
  git config --global user.email ka.kaosf@gmail.com
  git config --global github.user kaosf
  git config --global core.editor vim
  git config --global core.excludesfile $HOME/.gitignore
  git config --global color.ui true
  git config --global merge.ff false
  git config --global pull.rebase true
  git config --global alias.br branch
  git config --global alias.ci commit
  git config --global alias.co checkout
  git config --global alias.st status
  if [ ! -f $HOME/local/bin/diff-highlight ]; then
    mkdir -p $HOME/local/bin
    if which curl > /dev/null 2>&1; then
      curl https://gist.githubusercontent.com/kaosf/f563e42e57bfa19a5e07/raw/22ff20413b5f0fa8db32d39958ea8f96ef3ee719/diff-highlight > $HOME/local/bin/diff-highlight
    else
      wget https://gist.githubusercontent.com/kaosf/f563e42e57bfa19a5e07/raw/22ff20413b5f0fa8db32d39958ea8f96ef3ee719/diff-highlight -O $HOME/local/bin/diff-highlight
    fi
    chmod +x $HOME/local/bin/diff-highlight
  fi
  git config --global pager.log 'diff-highlight | less'
  git config --global pager.show 'diff-highlight | less'
  git config --global pager.diff 'diff-highlight | less'
  git config --global push.default simple
fi

if [ ! -s $HOME/.lesskey ]; then
  ln -sf $PWD/.lesskey $HOME/.lesskey
  lesskey
fi

if [ -f $HOME/.tmux.conf ]; then
  rm $HOME/.tmux.conf
fi
cp $PWD/.tmux.conf $HOME/.tmux.conf
# used-mem
if [ ! -f $HOME/local/bin/used-mem ]; then
  mkdir -p $HOME/local/bin
  if which curl > /dev/null 2>&1; then
    curl https://gist.githubusercontent.com/kaosf/6058eab04613bc263d77/raw/a95510680cfd59a2f25b6964c123426a6ff3254a/used-mem > $HOME/local/bin/used-mem
  else
    wget https://gist.githubusercontent.com/kaosf/6058eab04613bc263d77/raw/a95510680cfd59a2f25b6964c123426a6ff3254a/used-mem -O $HOME/local/bin/used-mem
  fi
  chmod +x $HOME/local/bin/used-mem
fi
# Switch Mac or others
if which sw_vers > /dev/null 2>&1; then
  cat $PWD/.tmux.conf-for-mac >> $HOME/.tmux.conf
else
  cat $PWD/.tmux.conf-for-linux >> $HOME/.tmux.conf
fi

if [ ! -f $HOME/.muttrc ]; then
  cp $PWD/.muttrc $HOME/.muttrc
fi

[ -f $HOME/.vimshrc ] && rm $HOME/.vimshrc
cp $PWD/.aliases $HOME/.vimshrc

# Bash
if [ ! -L $HOME/.bashrc ]; then
  if [ -f $HOME/.bashrc ]; then
    mv $HOME/.bashrc $HOME/.bashrc.orig
  fi
fi
ln -sf $PWD/.bashrc $HOME/.bashrc
ln -sf $PWD/.bash_aliases $HOME/.bash_aliases
# Debian or Ubuntu
if \
  uname -ar | grep debian > /dev/null 2>&1 || \
  uname -ar | grep Ubuntu > /dev/null 2>&1
then
  ln -sf $PWD/.bashrc-prompt-debian $HOME/.bashrc-prompt-debian
else
  ln -sf $PWD/.bashrc-prompt $HOME/.bashrc-prompt
fi
