#! /bin/sh

ln -s $PWD/.bashrc \
      $HOME/.bashrc
ln -s $PWD/.zshrc \
      $HOME/.zshrc
ln -s $PWD/.vimrc \
      $HOME/.vimrc
ln -s $PWD/.tmux.conf \
      $HOME/.tmux.conf
if [ ! -d $HOME/.emacs.d ]
then
  mkdir $HOME/.emacs.d
fi
ln -s $PWD/.emacs.d_init.el $HOME/.emacs.d/init.el
if [ ! -d $HOME/.lein ]
then
  mkdir $HOME/.lein
fi
if [ ! -f $HOME/.lein/profiles.clj ]
then
  cp $PWD/.lein_profiles.clj $HOME/.lein/profiles.clj
fi
if [ `which git` ]
then
  git config --global user.name ka
  git config --global user.email ka.kaosf@gmail.com
  git config --global core.editor vim
  git config --global color.ui true
  git config --global github.user kaosf
  git config --global merge.ff false
  git config --global pull.rebase true
fi
