#!/bin/bash

for i in \
  .aliases \
  .bashrc \
  .bash_aliases \
  .envvars \
  .zshrc \
  .zshrc-functions \
  .zshrc-peco \
  .zshrc-prompt \
  .zshrc-warnings \
  .vimrc \
  .vimrc-neocomplete \
  .vimrc-neosnippet \
  .tigrc \
  .gemrc \
  .pryrc \
  .guard.rb \

do
  if [ ! -s $HOME/$i ]; then
    ln -sf $PWD/$i $HOME/$i
  fi
done

if [ ! -d $HOME/.emacs.d ]; then
  mkdir $HOME/.emacs.d
fi
if [ ! -s $HOME/.emacs.d/init.el ]; then
  ln -sf $PWD/.emacs.d_init.el $HOME/.emacs.d/init.el
fi

if [ ! -d $HOME/.lein ]; then
  mkdir $HOME/.lein
fi
if [ ! -f $HOME/.lein/profiles.clj ]; then
  cp $PWD/.lein_profiles.clj $HOME/.lein/profiles.clj
fi

if [ `which git` ]; then
  if [ ! -f $HOME/.gitignore ]; then
    ln -sf $PWD/.gitignore-global $HOME/.gitignore
  fi
  git config --global user.name ka
  git config --global user.email ka.kaosf@gmail.com
  git config --global github.user kaosf
  git config --global core.editor vim
  git config --global core.excludesfile $HOME/.gitignore
  git config --global color.ui true
  git config --global merge.ff false
  git config --global pull.rebase true
  git config --global alias.br branch
  git config --global alias.ci commit
  git config --global alias.co checkout
  git config --global alias.st status
  if [ ! -f $HOME/local/bin/diff-highlight ]; then
    wget https://raw.githubusercontent.com/git/git/7a1aa0c28876e044351e78d8b8ae6cdbb10b5dfe/contrib/diff-highlight/diff-highlight
    wget https://gist.githubusercontent.com/kaosf/b6392be33be2e8af7904/raw/6a0f089b79ea456c2798db61381affa9f4769f16/diff-highlight.utf8.patch
    patch -u diff-highlight < diff-highlight.utf8.patch
    rm diff-highlight.utf8.patch
    mkdir -p $HOME/local/bin
    chmod +x diff-highlight
    mv diff-highlight $HOME/local/bin
  fi
  git config --global pager.log 'diff-highlight | less'
  git config --global pager.show 'diff-highlight | less'
  git config --global pager.diff 'diff-highlight | less'
  git config --global push.default simple
fi

if [ ! -s $HOME/.lesskey ]; then
  ln -sf $PWD/.lesskey $HOME/.lesskey
  lesskey
fi

[ -f $HOME/.tmux.conf ] && rm $HOME/.tmux.conf
if [[ $1 = nostatus ]]; then
  cp $PWD/.tmux.conf-nostatus $HOME/.tmux.conf
  shift
else
  cp $PWD/.tmux.conf $HOME/.tmux.conf
fi
# used-mem
if [ ! -f $HOME/local/bin/used-mem ]; then
  mkdir -p $HOME/local/bin
  wget https://gist.githubusercontent.com/kaosf/6058eab04613bc263d77/raw/a95510680cfd59a2f25b6964c123426a6ff3254a/used-mem -O $HOME/local/bin/used-mem
  chmod $HOME/local/bin/used-mem
fi
# Switch Mac or others
if which sw_vers > /dev/null 2>&1; then
  cat $PWD/.tmux.conf-for-mac >> $HOME/.tmux.conf
else
  cat $PWD/.tmux.conf-for-linux >> $HOME/.tmux.conf
fi

[ -f $HOME/.vimshrc ] && rm $HOME/.vimshrc
cp $PWD/.aliases $HOME/.vimshrc
