#!/bin/bash

for i in \
  .aliases \
  .bashrc \
  .bash_aliases \
  .envvars \
  .zshrc \
  .zshrc-functions \
  .zshrc-peco \
  .zshrc-prompt \
  .zshrc-warnings \
  .vimrc \
  .vimrc-neocomplete \
  .vimrc-neosnippet \
  .tigrc \
  .gemrc \
  .pryrc \
  .guard.rb \

do
  if [ ! -s $HOME/$i ]; then
    ln -sf $PWD/$i $HOME/$i
  fi
done

if [ ! -d $HOME/.emacs.d ]; then
  mkdir $HOME/.emacs.d
fi
if [ ! -s $HOME/.emacs.d/init.el ]; then
  ln -sf $PWD/.emacs.d_init.el $HOME/.emacs.d/init.el
fi

if [ ! -d $HOME/.lein ]; then
  mkdir $HOME/.lein
fi
if [ ! -f $HOME/.lein/profiles.clj ]; then
  cp $PWD/.lein_profiles.clj $HOME/.lein/profiles.clj
fi

if [ `which git` ]; then
  if [ ! -f $HOME/.gitignore ]; then
    ln -sf $PWD/.gitignore-global $HOME/.gitignore
  fi
  if [ ! -f $HOME/.gitconfig ]; then
    echo 'Input your name for Git author.'
    echo -n '> '
    git config --global user.name `read line; echo $line`
    while :; do
      echo 'Input your Email address for Git author.'
      echo -n '> '
      read EMAIL
      echo 'Input again for confirmation.'
      echo -n '> '
      read EMAIL_CONFIRM
      if [[ $EMAIL = $EMAIL_CONFIRM ]]; then break; fi
      echo 'Do not match. Input again.'
    done
    git config --global user.email $EMAIL
    echo 'Input your name on GitHub.'
    echo -n '> '
    git config --global github.user `read line; echo $line`
  fi
  git config --global core.editor vim
  git config --global core.excludesfile $HOME/.gitignore
  git config --global color.ui true
  git config --global merge.ff false
  git config --global pull.rebase true
  git config --global alias.br branch
  git config --global alias.ci commit
  git config --global alias.co checkout
  git config --global alias.st status
  if [ ! -f $HOME/local/bin/diff-highlight ]; then
    mkdir -p $HOME/local/bin
    wget https://gist.githubusercontent.com/kaosf/f563e42e57bfa19a5e07/raw/22ff20413b5f0fa8db32d39958ea8f96ef3ee719/diff-highlight -O $HOME/local/bin/diff-highlight
    chmod +x $HOME/local/bin/diff-highlight
  fi
  git config --global pager.log 'diff-highlight | less'
  git config --global pager.show 'diff-highlight | less'
  git config --global pager.diff 'diff-highlight | less'
  git config --global push.default simple
fi

if [ ! -s $HOME/.lesskey ]; then
  ln -sf $PWD/.lesskey $HOME/.lesskey
  lesskey
fi

[ -f $HOME/.tmux.conf ] && rm $HOME/.tmux.conf
if [[ $1 = nostatus ]]; then
  cp $PWD/.tmux.conf-nostatus $HOME/.tmux.conf
  shift
else
  cp $PWD/.tmux.conf $HOME/.tmux.conf
fi
# used-mem
if [ ! -f $HOME/local/bin/used-mem ]; then
  mkdir -p $HOME/local/bin
  wget https://gist.githubusercontent.com/kaosf/6058eab04613bc263d77/raw/a95510680cfd59a2f25b6964c123426a6ff3254a/used-mem -O $HOME/local/bin/used-mem
  chmod $HOME/local/bin/used-mem
fi
# Switch Mac or others
if which sw_vers > /dev/null 2>&1; then
  cat $PWD/.tmux.conf-for-mac >> $HOME/.tmux.conf
else
  cat $PWD/.tmux.conf-for-linux >> $HOME/.tmux.conf
fi

[ -f $HOME/.vimshrc ] && rm $HOME/.vimshrc
cp $PWD/.aliases $HOME/.vimshrc
