#!/bin/bash

for i in \
  .xmodmap \
  .xmodmap-revert \

do
  rm $HOME/$i
  cp $PWD/$i $HOME/$i
done

#if [ ! -f /etc/lsb-release ]; then
if [ -f /etc/arch-release ]; then
  cat <<EOS >> $HOME/.xmodmap
! Caps Lock -> Ctrl
remove Lock = Caps_Lock
keysym Caps_Lock = Control_L
add Control = Control_L
EOS
fi

for i in \
  .gvimrc \
  .vimperatorrc \

do
  if [ ! -s $HOME/$i ]; then
    ln -sf $PWD/$i $HOME/$i
  fi
done

if [ ! -f $HOME/.vim/colors/desert256.vim ]; then
  mkdir -p $HOME/.vim/colors
  if which curl > /dev/null 2>&1; then
    curl 'http://www.vim.org/scripts/download_script.php?src_id=4055' > $HOME/.vim/colors/desert256.vim
  else
    wget 'http://www.vim.org/scripts/download_script.php?src_id=4055' -O $HOME/.vim/colors/desert256.vim
  fi
fi

if [[ $1 == menukey ]]; then
  cat $PWD/.xmodmap-for-menukey        >> $HOME/.xmodmap
  cat $PWD/.xmodmap-for-menukey-revert >> $HOME/.xmodmap-revert
fi

mkdir -p $HOME/.config/awesome
[ -f $HOME/.config/awesome/rc.lua ] || \
  ln -sf $PWD/.config/awesome/rc.lua $HOME/.config/awesome/rc.lua
[ -f $HOME/.config/awesome/theme.lua ] || \
  ln -sf $PWD/.config/awesome/theme.lua $HOME/.config/awesome/theme.lua
