#!/bin/bash

for i in \
  .xmodmap \
  .xmodmap-revert \

do
  rm $HOME/$i
  cp $PWD/$i $HOME/$i
done

for i in \
  .gvimrc \
  .vimperatorrc \
  .xmodmap-for-hhkb \
  .xmodmap-for-hhkb-revert \

do
  if [ ! -s $HOME/$i ]; then
    ln -s $PWD/$i $HOME/$i
  fi
done

if [ -d $HOME/local/bin ]; then
  echo 'xmodmap $HOME/.xmodmap-for-hhkb' \
    > $HOME/local/bin/hhkb-start
  chmod +x $HOME/local/bin/hhkb-start
  echo 'xmodmap $HOME/.xmodmap-for-hhkb-revert' \
    > $HOME/local/bin/hhkb-finish
  chmod +x $HOME/local/bin/hhkb-finish
fi

if [[ $1 == menukey ]]; then
  cat $PWD/.xmodmap-for-menukey        >> $HOME/.xmodmap
  cat $PWD/.xmodmap-for-menukey-revert >> $HOME/.xmodmap-revert
fi

mkdir -p $HOME/.config/awesome
[ ! -f $HOME/.config/awesome/rc.lua ] && \
  ln -s $PWD/.config/awesome/rc.lua $HOME/.config/awesome/rc.lua
[ ! -f $HOME/.config/awesome/theme.lua ] && \
  ln -s $PWD/.config/awesome/theme.lua $HOME/.config/awesome/theme.lua
